version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      typescript:
        patterns:
          - typescript
      biome:
        patterns:
          - '@biomejs/*'
      vitest:
        patterns:
          - vitest
          - '@vitest/*'
      build:
        patterns:
          - tsup
          - publint
          - '@arethetypeswrong/*'
          - size-limit
          - '@size-limit/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
