import { type NetworkName } from 'networks/types';

export const assetIds: Record<NetworkName, Record<string, string>> = {
  custom: {
    WAVES: 'WAVES',
  },
  mainnet: {
    BAG: 'Euz5HtYcj3nVTZxppA7wdabwTe5BzHFiu4QG1EJtzeUx',
    BCH: 'zMFqXuoyrn5w17PFurTqxB7GsS71fp9dfk6XFwxbPCy',
    BNB: '5UYBPpq4WoU5n4MwpFkgJnW3Fq4B1u3ukpK33ik4QerR',
    BNT: 'F81SdfzBZr5ce8JArRWLPJEDg1V8yT257ohbcHk75yCp',
    BSV: '62LyMjcr2DtiyF5yVXFhoQ2q414VPPJXjsNYp72SuDCH',
    BTC: '8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS',
    BUSD: '8DLiYZjo3UUaRBTHU7Ayoqg4ihwb6YH1AfXrrhdjQ7K1',
    CGU: 'HK72uehJjkM22phZ5wHhBYxprP3r41eYtk9fYu5uetne',
    CRV: '3KhNcHo4We1G5EWps7b1e5DTdLgWDzctc8S6ynu37KAb',
    DAI: '8zUYbdB8Q6mDhpcXYv52ji8ycfj4SDX4gJXS7YY3dA4R',
    DASH: 'B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H',
    DUXPLORER: 'usUeJwSpvghP5FR6jE9X4fUJbgXyxXnAezSgbzoMA8K',
    EAST: '3UHgFQECoynwC3iunYBnbhzmcCzC5gVnVZMv8Yw1bneK',
    EFYT: '725Yv9oceWsB4GsYwyy4A52kEwyVrL5avubkeChSnL46',
    EGG: 'C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS',
    EGGMOON: 'J3dRSWWyRoX55YuuXQhBa2uZ4bUczkqSFC94VZeCoWKA',
    EGGPOINT: '6pHc1PyBcXyS74eBEo95V3ecQvhAypL9RfsUUKtHDUq2',
    EGGSEGGS: 'E4cL4MDRTPz9Wo1hHkxQv4ZzpxVL5136JVaki4wGz2QZ',
    ENDO: '6muMrLavuvuSZXgy1cQrvYm92rGbprNXGdj6Bg7HAtTV',
    ENNO: '7LMV3s1J4dKpMQZqge5sKYoFkZRLojnnU49aerqos4yg',
    ERG: '5dJj4Hn9t2Ve3tRpNGirUHy4yBK6qdJRAJYV21yPPuGz',
    ETH: '474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu',
    EUR: 'Gtb1WRznfchDnTh37ezoDTJ4wcoKaRsKqKjJjy7nm2zU',
    EURN: 'DUk2YTxhRoAqMJLus4G2b3fR8hMHVh6eiyFx5r29VR6t',
    FL: 'Crpz6B3cbntgAtb6G7WtZb6ArdifE3QypdxpbaofwKVd',
    FOMO: 'J4iWJS2kGmAqLC4dYFuHvmqXK1E6rBJaRTA6nd1VmFkj',
    FORKLOG: '4q9KXJCi9ZbmhttXuLRabd9epgpvowVuyKDuuNdkahdC',
    FTM: '4GZH8rk5vDmMXJ81Xqfm3ovFaczqMnQ11r7aELiNxWBV',
    KOLKHOZ: 'BwCk5zUMTuYtFFu3euo3g6Fwdk7TALrr5C8wvdzps8R5',
    LINK: '2bbGhKo5C31iEiB4CwGuqMYwjD7gCA9eXmm51fe2v8vT',
    LTC: 'HZk1mbfuJpmxU1Fs4AX5MWLVYtctsNcg6e2C6VKqK8zk',
    MARVIN: '6xxMPcvHneBvZk7p82oUdQw4J3F9bsFgtm7YYXQSEDxb',
    MATH: 'FPzcaiEjyG6syoXLY1aghWdPwExvRezGbPXjmL3Gcofw',
    MATIC: 'HcHacFH51pY91zjJa3ZiUVWBww54LnsL4EP3s7hVGo9L',
    MUNA: 'eCNH1aqUnocub8PbNsxLNvZWGeVE98L2Crw3cGY6Gq2',
    MUNDO: '2x8vsNgrBgLq9GWpnTNSVXTGq3cMLSvWWepR8CX36fVZ',
    NGNT: 'H6CwbwXMRKRw6jb1dRUMVs2N6Sdg2wQcXPRaRkjZSjYU',
    NSBT: '6nSpVyNH7yM69eg446wrQR94ipbbcmZMU1ENPwanC97g',
    PESOLATINO: '5JQ8yUY4vnB19s4bXSGVYsNEyA9Bag6jbMtVEgFHvYM7',
    PUZZLE: 'HEB8Qaw9xrWpWs8tHsiATYGBWDBtP2S7kcPALrMu43AS',
    RACE: 'D4TPjtzpsDEJFS1pUAkvh1tJJJMNWGcSrds9sveBoQka',
    SCONEX: 'EnBAWjayxUrwL7KMTBvRzcS5RqGYwFfLPD4tFVu4Mpj3',
    SHEG: 'A2hcw6RV23Fc8Y8FNfV35Sq5QeS9Tgp6n8hbrESiRvXX',
    SHIB: 'GVxGPBtgVWMW1wHiFnfaCakbJ6sKgZgowJgW5Dqrd7JH',
    SIGN: '9sQutD5HnRvjM1uui5cVC4w9xkMPAfYEV8ymug3Mon2Y',
    STREET: 'DAGQvqQg4F5YTQCQ5JFaVJdZEVoTvecuw2W9ybL5P1hR',
    SWOP: 'Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT',
    sNSBT: '8wUmN9Y15f3JR4KZfE81XLXpkdgwnqoBNG6NmocZpKQx',
    sNSBT_TCI: '4CDoUKSAtLTwVTpdxFu6EcbafiCDZUSBXrWGjrAcCPoL',
    TN: 'bPWkA3MNyEr1TuDchWgdpqJZhGhfPXj7dJdr3qiW2kD',
    TRY: '2mX5DzVKWrAJw8iwdJnV2qtoeVG9h5nTDpTqC1wb1WEN',
    TSN: '8t4DPWTwPzpatHA9AkTxWAB47THnYzBsDnoY7fQqbG91',
    TURTLE: '9mFbBseP3RSC2veLrBgiLJMXDjahwBiH44WnqMfdkgid',
    UNI: '4YmM7mj3Av4DPvpNpbtK4jHbpzYDcZuY6UUnYpqTbzLj',
    USDAP: 'CsUiySsn7Sq747qG9vT1vtqfZNecheSyUpFeAHGMxQCM',
    USDC: '6XtHjpXbs9RRJP2Sr9GUyVqzACcby9TkThHXnjVC5CDJ',
    USDCLP: 'CrjhbC9gRezwvBZ1XwPQqRwx4BWzoyMHGFNUVdn22ep6',
    USDN: 'DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p',
    USDT: '34N9YcEETLWn93qYQ64EsP1x89tSruJU44RrEMSXXEPJ',
    USDTLP: '9AT2kEi8C4AYxV1qKxtQTVpD5i54jCPvaNNRP6VzRtYZ',
    VIRES: 'DSbbhLsSTeDg5Lsiufk2Aneh3DjVqJuPr2M9uU1gwy5p',
    VIRES_USDC_LP: 'FSRHtSyXRXQjzQLRtmaqFpBDDCNjY8PU8KNtwoGXVBmr',
    VIRES_USDT_LP: '2tVLdi5fQXk2JcuDAojhctnDp5B5PZhNMyj5GUpeC3tZ',
    WAVES: 'WAVES',
    WCT: 'DHgwrRvVyqJsepd32YbBqUeDH4GJ1N984X8QoekjgH8J',
    WEST: '4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8',
    WNET: 'AxAmJaro7BJ4KasYiZhw7HkjwgYtt2nekPuF2CN9LMym',
    WX: 'Atqv59EYzjFGuitKVnMRk6H8FukjoV3ktPorbEys25on',
    XMR: '5WvPKSJXzVE2orvbkJ8wsQmmQKqTv9sGBPksV4adViw3',
    YFI: 'BLRxWVJWaVuR2CsCoTvTw2bDZ3sQLeTbCofcJv7dP5J4',
    ZEC: 'BrjUWjndUanm5VsJkbUip8VRYy6LWJePtxya3FNv4TQa',
  },
  stagenet: {
    WAVES: 'WAVES',
  },
  testnet: {
    BTC: 'iHTVbu8ArLhtdtJ8BQhyaomgVogSfXT45RtwNFiK4We',
    DASH: '13mWHq1h58WRTiRNBqDRD63gsV8Hq4joxYQzH3iRdHiR',
    EGG: 'Gp75gygbc1woJMheDomSY1ULyaRVGVEWS64wNWfvncyg',
    ETH: '8Ye7AVyY8TgWbNfQdriLRCBGEPXTb5T48EeBgJTQADNs',
    EURN: 'ECBCkHS68DckpBrzLeoRgYbFg7sCVqR176mPqbXsj9pA',
    LTC: 'Ea5Y9FAfV3MRL2yQHbQXZvjjWtCJ8gvjYcBCfMTaT7TG',
    NSBT: '36mg8NZTaFRDygiVwb8uBnLR51hetJruUCZcxhaVcHj9',
    RACE: 'CzfHm2WKdQoKQeGfosLsmKd6kAcuxHMsjjm9M7c1FUtg',
    SWOP: '2HAJrwa8q4SxBx9cHYaBTQdBjdk5wwqdof7ccpAx2uhZ',
    USDN: '8UrfDVd5GreeUwm7uPk7eYz1eMv376kzR52C6sANPkwS',
    USDT: 'Had29UYhBkBGa7r1gu5ktr3okMz4e8vWPXzxTXNJUF6H',
    WAVES: 'WAVES',
    XMR: 'Eox8Cb2cfkFrsYMJSN8TmyfqzbqwjQp4sdJDE6PA9hph',
    ZEC: 'DeiUipcLutVxVVuHxpU8QUZos6KZpnrxakku5YpZSBaT',
  },
};

export const defaultAssetTickers = {
  '2bbGhKo5C31iEiB4CwGuqMYwjD7gCA9eXmm51fe2v8vT': 'LINK',
  '2R57nL7ftpuwbgdprcmAeA9i7ykLH6A4wzLkZHWPiHKc': 'EGGMOON',
  '2tVLdi5fQXk2JcuDAojhctnDp5B5PZhNMyj5GUpeC3tZ': 'VIRES_USDT_LP',
  '2x8vsNgrBgLq9GWpnTNSVXTGq3cMLSvWWepR8CX36fVZ': 'MUNDO',
  '3iAUM9xnKdu2TWBXRqPvYoGsbiZEbDPP1okUf5v9RJNz': 'AUSDTLPM',
  '3KhNcHo4We1G5EWps7b1e5DTdLgWDzctc8S6ynu37KAb': 'CRV',
  '3UHgFQECoynwC3iunYBnbhzmcCzC5gVnVZMv8Yw1bneK': 'EAST',
  '4CDoUKSAtLTwVTpdxFu6EcbafiCDZUSBXrWGjrAcCPoL': 'sNSBT_TCI',
  '4GZH8rk5vDmMXJ81Xqfm3ovFaczqMnQ11r7aELiNxWBV': 'FTM',
  '4K35syPfY2tYrNWzjh1vbmH39qE4qPV7SwLwekrzD82r': 'USDTLAMBO',
  '4kwKSf4Bx2Wq8YxKnVZBhcEHyXzEtJ2pw7ixfJgirwf2': 'MUNDO',
  '4LHHvYGNKJUg5hj65aGD5vgScvCBmLpdRFtjokvCjSL8': 'WEST',
  '4NyYnDGopZvEAQ3TcBDJrJFWSiA2xzuAw83Ms8jT7WuK': 'ABTCLPM',
  '4q9KXJCi9ZbmhttXuLRabd9epgpvowVuyKDuuNdkahdC': 'FORKLOG',
  '4YmM7mj3Av4DPvpNpbtK4jHbpzYDcZuY6UUnYpqTbzLj': 'UNI',
  '5bcAh1r6ydrpk44FEmrnmJQjumgKo3NKEEsyfgmZYwxC': 'TURTLE',
  '5dJj4Hn9t2Ve3tRpNGirUHy4yBK6qdJRAJYV21yPPuGz': 'ERG',
  '5HGPPLj58XUx3ryMgkASJoqYq33zwBbTMf1CGxfKw6jp': 'ENDO',
  '5JQ8yUY4vnB19s4bXSGVYsNEyA9Bag6jbMtVEgFHvYM7': 'PESOLATINO',
  '5m5stLsMZSPomwxTTjJGMMEnjMafRMfap5vZyaLwgMKD': 'KOLKHOZ',
  '5NmV5VAhkqormdwvaQjE54yPEkNwSRtcXxhLkJbVQqkN': 'NGNN',
  '5nk9JW8yRonyNBEwhChoksLxpBECVxbVLqaNuQs9EJn1': 'PESOLATINO',
  '5UYBPpq4WoU5n4MwpFkgJnW3Fq4B1u3ukpK33ik4QerR': 'BNB',
  '5WvPKSJXzVE2orvbkJ8wsQmmQKqTv9sGBPksV4adViw3': 'XMR',
  '6gtgBD12xZkUTnzGofoFJpMg5gYG1FP6PaGyLviVQjbh': 'ETHUSDNLP',
  '6muMrLavuvuSZXgy1cQrvYm92rGbprNXGdj6Bg7HAtTV': 'ENDO',
  '6nSpVyNH7yM69eg446wrQR94ipbbcmZMU1ENPwanC97g': 'NSBT',
  '6pHc1PyBcXyS74eBEo95V3ecQvhAypL9RfsUUKtHDUq2': 'EGGPOINT',
  '6XtHjpXbs9RRJP2Sr9GUyVqzACcby9TkThHXnjVC5CDJ': 'USDC',
  '6xxMPcvHneBvZk7p82oUdQw4J3F9bsFgtm7YYXQSEDxb': 'MARVIN',
  '7KZbJrVopwJhkdwbe1eFDBbex4dkY63MxjTNjqXtrzj1': 'WAVESUSDNLP',
  '7LMV3s1J4dKpMQZqge5sKYoFkZRLojnnU49aerqos4yg': 'ENNO',
  '7TiEKGoXwFXiQCKqj8773QJFY4tCrK3Yku9Q4zenJdPn': 'AUSDCLPA',
  '8b53M5vTk8wRBRuJ27ebTvTeGfbjpLZuoZQ7hkFjHsu4': 'BTCUP',
  '8DLiYZjo3UUaRBTHU7Ayoqg4ihwb6YH1AfXrrhdjQ7K1': 'BUSD',
  '8HYDtqEuHj3RDcwR8yxEvPq1qQSB9FazC8wMHtRb2TFe': 'MTNT',
  '8inca5fv4xr6KZtRMRPYr7vADfk8fd6G2z1gMoRkbUYS': 'JPYN',
  '8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS': 'BTC',
  '8t4DPWTwPzpatHA9AkTxWAB47THnYzBsDnoY7fQqbG91': 'TSN',
  '8WhH5CCJ6NakPvEvAJcizqqD7H6axhupdYHDFumSDwsy': 'BTCUSDNLP',
  '8wUmN9Y15f3JR4KZfE81XLXpkdgwnqoBNG6NmocZpKQx': 'sNSBT',
  '8zKqZF6asB6yiK8rv9nMUkJ7wAVBJndSmkC7SXJhRrM3': 'UAHN',
  '8zUYbdB8Q6mDhpcXYv52ji8ycfj4SDX4gJXS7YY3dA4R': 'DAI',
  '9AT2kEi8C4AYxV1qKxtQTVpD5i54jCPvaNNRP6VzRtYZ': 'USDTLP',
  '9FgLbjiwhn7wFEviVayHNpUV3WnDWJnox9HS5xpcHNDH': 'BLXS',
  '9LNqjybyCX1oexCub4yY7hdJf6aeP4HeV5LpsjcNHwRR': 'CNYN',
  '9mFbBseP3RSC2veLrBgiLJMXDjahwBiH44WnqMfdkgid': 'TURTLE',
  '9sQutD5HnRvjM1uui5cVC4w9xkMPAfYEV8ymug3Mon2Y': 'SIGN',
  '34N9YcEETLWn93qYQ64EsP1x89tSruJU44RrEMSXXEPJ': 'USDT',
  '45WTLz6e3Ek8Ffe7QHMkQ2TwfozfWsrodTHMtPyTMNtt': 'WAVESDOWN',
  '46PdJcKzDuYfzLuLNjffM3F8jR8hL357V9AdGK2xN3kx': 'FORKLOG',
  '54UszKAj3MtYmkdRCqSXAcaQLaVALBy7CCrVkfmfzhxR': 'EGGSEGGS',
  '62LyMjcr2DtiyF5yVXFhoQ2q414VPPJXjsNYp72SuDCH': 'BSV',
  '97zHFp1C3cB7qfvx8Xv5f2rWp9nUSG5UnAamfPcW6txf': 'USDTUSDNLP',
  '474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu': 'ETH',
  A2hcw6RV23Fc8Y8FNfV35Sq5QeS9Tgp6n8hbrESiRvXX: 'SHEG',
  A9h1bQ2ycMPmS85Dp5NECymsoJ48ZrK8eThdECJZW94b: 'AUSDCLPM',
  AbunLGErT5ctzVN8MVjb4Ad9YgjpubB8Hqb17VxzfAck: 'WW',
  AEhWyMGY3twQdPQSCqVSdVqxcgzyEn129ipzvbqtTcyv: 'USDFL',
  Atqv59EYzjFGuitKVnMRk6H8FukjoV3ktPorbEys25on: 'WX',
  B1dG9exXzJdFASDF2MwCE7TYJE5My4UgVRx43nqDbF6s: 'ABTCLPC',
  B3uGHFRpSUuGEDWjqB9LWWxafQj8VTvpMucEyoxzws5H: 'DASH',
  B543bkZcZNo5GrUnd5fxB6EwkiJhAVyKCkPn5nWzZC2s: 'MATH',
  BLRxWVJWaVuR2CsCoTvTw2bDZ3sQLeTbCofcJv7dP5J4: 'YFI',
  BrjUWjndUanm5VsJkbUip8VRYy6LWJePtxya3FNv4TQa: 'ZEC',
  BwCk5zUMTuYtFFu3euo3g6Fwdk7TALrr5C8wvdzps8R5: 'KOLKHOZ',
  bPWkA3MNyEr1TuDchWgdpqJZhGhfPXj7dJdr3qiW2kD: 'TN',
  C1iWsKGqLwjHUndiQ7iXpdmPum9PeCDFfyXBdJJosDRS: 'EGG',
  CE5cxMvz7865CyFZPFUmDiL4KRkYXP6b6oYgN3vmWdV5: 'STREET',
  CrjhbC9gRezwvBZ1XwPQqRwx4BWzoyMHGFNUVdn22ep6: 'USDCLP',
  Crpz6B3cbntgAtb6G7WtZb6ArdifE3QypdxpbaofwKVd: 'FL',
  CsUiySsn7Sq747qG9vT1vtqfZNecheSyUpFeAHGMxQCM: 'USDAP',
  D4TPjtzpsDEJFS1pUAkvh1tJJJMNWGcSrds9sveBoQka: 'RACE',
  DAGQvqQg4F5YTQCQ5JFaVJdZEVoTvecuw2W9ybL5P1hR: 'STREET',
  DazN41oAedqwGZ8aabf4nJQwJNZhsEgPH3YQWDtPsdeV: 'BTCLP',
  Dfx6LJPndo1h5Umk9SofDhMDs6Gi8cHyT3873pSgoASU: 'FOMO',
  DG2xFkPdDwKUoBkzGAhQtLpSGzfXLiCYPEzeKH2Ad24p: 'USDN',
  DGbqkzM6Ds5NAF2B3GHYfyZRmWKt7xLYRYcwpMm7D6V4: 'TRYN',
  DHgwrRvVyqJsepd32YbBqUeDH4GJ1N984X8QoekjgH8J: 'WCT',
  DhaaqiG8xz8njeBuMtTM2G6avg9Jdhfrxw5onm5GaXx1: 'GBPN',
  DRVGiwqmsZpFzaMoAFQXjBNXT4PFepgPvnJ5sGUrhXQt: 'BTCDOWN',
  DSbbhLsSTeDg5Lsiufk2Aneh3DjVqJuPr2M9uU1gwy5p: 'VIRES',
  DUk2YTxhRoAqMJLus4G2b3fR8hMHVh6eiyFx5r29VR6t: 'EURN',
  DxFwXxS1r3uZ2QEiSqhe6uoXMJBsz4ShLtHvr4HDzNri: 'BRLN',
  E4cL4MDRTPz9Wo1hHkxQv4ZzpxVL5136JVaki4wGz2QZ: 'EGGSEGGS',
  EemDhgzLQ57hjFbNGYkPJtCnSz5eP2YdMa6H4Pum92z8: 'AUSDTLPC',
  EfdcPXw7o7rrrPWmMBr2sa66Dk95n56622ngujbaGhye: 'DUXPLORER',
  Ehie5xYpeN8op1Cctc6aGUrqx8jq3jtf1DSjXDbfm7aT: 'SWOP',
  Ej7kEzxvUsoiMtJKiuFpMD9tC6qfCADpZynyW2vqcWW: 'EGGPOINT',
  ELzXTgPa6GGYyLtitn2oWDWQ9joyTFEueNtF4kxg95dM: 'ETHLP',
  EnBAWjayxUrwL7KMTBvRzcS5RqGYwFfLPD4tFVu4Mpj3: 'SCONEX',
  ESaD2AREvgk7o4C9eQkZ8Nmau9BSHqgTK5ymHV36xocy: 'CGU',
  Euz5HtYcj3nVTZxppA7wdabwTe5BzHFiu4QG1EJtzeUx: 'BAG',
  eCNH1aqUnocub8PbNsxLNvZWGeVE98L2Crw3cGY6Gq2: 'MUNA',
  eWeMD5KNeuRaALCAb4uuJKtAvon2JcTyXQyoBMhuN2X: 'RUBN',
  F2AKkA513k5yHEJkLsU6vWxCYYk811GpjLhwEv2WGwZ9: 'WXUSDNLP',
  F81SdfzBZr5ce8JArRWLPJEDg1V8yT257ohbcHk75yCp: 'BNT',
  FaCgK3UfvkRF2WfFyKZRVasMmqPRoLG7nUv8HzR451dm: 'USDCLAMBO',
  FPzcaiEjyG6syoXLY1aghWdPwExvRezGbPXjmL3Gcofw: 'MATH',
  FSRHtSyXRXQjzQLRtmaqFpBDDCNjY8PU8KNtwoGXVBmr: 'VIRES_USDC_LP',
  GVxGPBtgVWMW1wHiFnfaCakbJ6sKgZgowJgW5Dqrd7JH: 'SHIB',
  H6CwbwXMRKRw6jb1dRUMVs2N6Sdg2wQcXPRaRkjZSjYU: 'NGNT',
  HcHacFH51pY91zjJa3ZiUVWBww54LnsL4EP3s7hVGo9L: 'MATIC',
  HEB8Qaw9xrWpWs8tHsiATYGBWDBtP2S7kcPALrMu43AS: 'PUZZLE',
  HiiB3SSS1c89J5qQ6RLTUx4qgszLMQS2WRC3wfGfaCF8: 'WAVESUP',
  HK72uehJjkM22phZ5wHhBYxprP3r41eYtk9fYu5uetne: 'CGU',
  Hp4dcR5hYUkrAUrNPazSWEFnt5rUr2suxa2AMo4KsFEf: 'AETHLPM',
  HZk1mbfuJpmxU1Fs4AX5MWLVYtctsNcg6e2C6VKqK8zk: 'LTC',
  J3dRSWWyRoX55YuuXQhBa2uZ4bUczkqSFC94VZeCoWKA: 'EGGMOON',
  J4iWJS2kGmAqLC4dYFuHvmqXK1E6rBJaRTA6nd1VmFkj: 'FOMO',
  J7UiL1tgEfPaHkrLCirqoyu4v6rVMDc6yPEV95ixorVB: 'AETHLPC',
  K9hzUfVF4Koc5BoihpK1v6GXEpukERCEHNuSRNt83F9: 'AUSDTLPA',
  usUeJwSpvghP5FR6jE9X4fUJbgXyxXnAezSgbzoMA8K: 'DUXPLORER',
  VGLLW8XE5wyMU9NzKNn1s3qSx9AJ1oG8j1xzgwKnaZv: 'AUSDCLPC',
  yDf4UTg4DS75sCNP7oC1HraTN4KHtqmd6WueTid4PF1: 'MARVIN',
  zMFqXuoyrn5w17PFurTqxB7GsS71fp9dfk6XFwxbPCy: 'BCH',
};

const logosByName: Record<string, string> = {
  BAG: new URL('./logos/BAG.svg', import.meta.url).toString(),
  BCH: new URL('./logos/BCH.svg', import.meta.url).toString(),
  BNB: new URL('./logos/BNB.svg', import.meta.url).toString(),
  BNT: new URL('./logos/BNT.svg', import.meta.url).toString(),
  BSV: new URL('./logos/BSV.svg', import.meta.url).toString(),
  BTC: new URL('./logos/BTC.svg', import.meta.url).toString(),
  BUSD: new URL('./logos/BUSD.svg', import.meta.url).toString(),
  CGU: new URL('./logos/CGU.webp', import.meta.url).toString(),
  CRV: new URL('./logos/CRV.svg', import.meta.url).toString(),
  DAI: new URL('./logos/DAI.svg', import.meta.url).toString(),
  DASH: new URL('./logos/DASH.svg', import.meta.url).toString(),
  DUXPLORER: new URL('./logos/DUXPLORER.webp', import.meta.url).toString(),
  EAST: new URL('./logos/EAST.svg', import.meta.url).toString(),
  EFYT: new URL('./logos/EFYT.svg', import.meta.url).toString(),
  EGG: new URL('./logos/EGG.svg', import.meta.url).toString(),
  EGGMOON: new URL('./logos/EGGMOON.webp', import.meta.url).toString(),
  EGGPOINT: new URL('./logos/EGGPOINT.webp', import.meta.url).toString(),
  EGGSEGGS: new URL('./logos/EGGSEGGS.webp', import.meta.url).toString(),
  ENDO: new URL('./logos/ENDO.webp', import.meta.url).toString(),
  ENNO: new URL('./logos/ENNO.svg', import.meta.url).toString(),
  ERG: new URL('./logos/ERG.svg', import.meta.url).toString(),
  ETH: new URL('./logos/ETH.svg', import.meta.url).toString(),
  EUR: new URL('./logos/EUR.svg', import.meta.url).toString(),
  EURN: new URL('./logos/EURN.svg', import.meta.url).toString(),
  FL: new URL('./logos/FL.svg', import.meta.url).toString(),
  FOMO: new URL('./logos/FOMO.webp', import.meta.url).toString(),
  FORKLOG: new URL('./logos/FORKLOG.webp', import.meta.url).toString(),
  FTM: new URL('./logos/FTM.svg', import.meta.url).toString(),
  KOLKHOZ: new URL('./logos/KOLKHOZ.webp', import.meta.url).toString(),
  LINK: new URL('./logos/LINK.svg', import.meta.url).toString(),
  LTC: new URL('./logos/LTC.svg', import.meta.url).toString(),
  MARVIN: new URL('./logos/MARVIN.webp', import.meta.url).toString(),
  MATH: new URL('./logos/MATH.webp', import.meta.url).toString(),
  MATIC: new URL('./logos/MATIC.svg', import.meta.url).toString(),
  MUNA: new URL('./logos/MUNA.svg', import.meta.url).toString(),
  MUNDO: new URL('./logos/MUNDO.webp', import.meta.url).toString(),
  NGNT: new URL('./logos/NGNT.svg', import.meta.url).toString(),
  NSBT: new URL('./logos/NSBT.svg', import.meta.url).toString(),
  PESOLATINO: new URL('./logos/PESOLATINO.webp', import.meta.url).toString(),
  PUZZLE: new URL('./logos/PUZZLE.svg', import.meta.url).toString(),
  RACE: new URL('./logos/RACE.svg', import.meta.url).toString(),
  SCONEX: new URL('./logos/SCONEX.svg', import.meta.url).toString(),
  SHEG: new URL('./logos/SHEG.webp', import.meta.url).toString(),
  SHIB: new URL('./logos/SHIB.svg', import.meta.url).toString(),
  SIGN: new URL('./logos/SIGN.svg', import.meta.url).toString(),
  STREET: new URL('./logos/STREET.svg', import.meta.url).toString(),
  SWOP: new URL('./logos/SWOP.svg', import.meta.url).toString(),
  sNSBT: new URL('./logos/sNSBT.webp', import.meta.url).toString(),
  sNSBT_TCI: new URL('./logos/sNSBT_TCI.svg', import.meta.url).toString(),
  TN: new URL('./logos/TN.svg', import.meta.url).toString(),
  TRY: new URL('./logos/TRY.svg', import.meta.url).toString(),
  TSN: new URL('./logos/TSN.svg', import.meta.url).toString(),
  TURTLE: new URL('./logos/TURTLE.webp', import.meta.url).toString(),
  UNI: new URL('./logos/UNI.svg', import.meta.url).toString(),
  USDAP: new URL('./logos/USDAP.svg', import.meta.url).toString(),
  USDC: new URL('./logos/USDC.svg', import.meta.url).toString(),
  USDCLP: new URL('./logos/USDCLP.svg', import.meta.url).toString(),
  USDN: new URL('./logos/USDN.svg', import.meta.url).toString(),
  USDT: new URL('./logos/USDT.svg', import.meta.url).toString(),
  USDTLP: new URL('./logos/USDTLP.svg', import.meta.url).toString(),
  VIRES: new URL('./logos/VIRES.svg', import.meta.url).toString(),
  VIRES_USDC_LP: new URL('./logos/USDC.svg', import.meta.url).toString(),
  VIRES_USDT_LP: new URL('./logos/USDT.svg', import.meta.url).toString(),
  WAVES: new URL('./logos/WAVES.svg', import.meta.url).toString(),
  WCT: new URL('./logos/WCT.svg', import.meta.url).toString(),
  WEST: new URL('./logos/WEST.svg', import.meta.url).toString(),
  WNET: new URL('./logos/WNET.svg', import.meta.url).toString(),
  WX: new URL('./logos/WX.svg', import.meta.url).toString(),
  XMR: new URL('./logos/XMR.svg', import.meta.url).toString(),
  YFI: new URL('./logos/YFI.svg', import.meta.url).toString(),
  ZEC: new URL('./logos/ZEC.svg', import.meta.url).toString(),
};

export const assetLogosByNetwork: Partial<{
  [network: string]: Partial<{
    [assetId: string]: string;
  }>;
}> = Object.fromEntries(
  Object.entries(assetIds).map(([network, nameToIdMap]) => [
    network,
    Object.fromEntries(Object.entries(nameToIdMap).map(([name, id]) => [id, logosByName[name]])),
  ]),
);
