// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blocks": {
    params: {};
  };
  "/blockfeed": {
    params: {};
  };
  "/blockdetail": {
    params: {};
  };
  "/transaction": {
    params: {};
  };
  "/address": {
    params: {};
  };
  "/asset": {
    params: {};
  };
  "/dexpairs": {
    params: {};
  };
  "/unconfirmedtransactions": {
    params: {};
  };
  "/distributiontool": {
    params: {};
  };
  "/transactionmap": {
    params: {};
  };
  "/networkstatistics": {
    params: {};
  };
  "/networkmap": {
    params: {};
  };
  "/peers": {
    params: {};
  };
  "/sustainability": {
    params: {};
  };
  "/node": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blocks" | "/blockfeed" | "/blockdetail" | "/transaction" | "/address" | "/asset" | "/dexpairs" | "/unconfirmedtransactions" | "/distributiontool" | "/transactionmap" | "/networkstatistics" | "/networkmap" | "/peers" | "/sustainability" | "/node" | "/home";
  };
  "Layout.tsx": {
    id: "Layout";
    page: "/" | "/blocks" | "/blockfeed" | "/blockdetail" | "/transaction" | "/address" | "/asset" | "/dexpairs" | "/unconfirmedtransactions" | "/distributiontool" | "/transactionmap" | "/networkstatistics" | "/networkmap" | "/peers" | "/sustainability" | "/node" | "/home";
  };
  "pages/Dashboard.tsx": {
    id: "pages/Dashboard";
    page: "/";
  };
  "pages/Blocks.tsx": {
    id: "pages/Blocks";
    page: "/blocks";
  };
  "pages/BlockFeed.tsx": {
    id: "pages/BlockFeed";
    page: "/blockfeed";
  };
  "pages/BlockDetail.tsx": {
    id: "pages/BlockDetail";
    page: "/blockdetail";
  };
  "pages/Transaction.tsx": {
    id: "pages/Transaction";
    page: "/transaction";
  };
  "pages/Address.tsx": {
    id: "pages/Address";
    page: "/address";
  };
  "pages/Asset.tsx": {
    id: "pages/Asset";
    page: "/asset";
  };
  "pages/DexPairs.tsx": {
    id: "pages/DexPairs";
    page: "/dexpairs";
  };
  "pages/UnconfirmedTransactions.tsx": {
    id: "pages/UnconfirmedTransactions";
    page: "/unconfirmedtransactions";
  };
  "pages/DistributionTool.tsx": {
    id: "pages/DistributionTool";
    page: "/distributiontool";
  };
  "pages/TransactionMap.tsx": {
    id: "pages/TransactionMap";
    page: "/transactionmap";
  };
  "pages/NetworkStatistics.tsx": {
    id: "pages/NetworkStatistics";
    page: "/networkstatistics";
  };
  "pages/NetworkMap.tsx": {
    id: "pages/NetworkMap";
    page: "/networkmap";
  };
  "pages/Peers.tsx": {
    id: "pages/Peers";
    page: "/peers";
  };
  "pages/Sustainability.tsx": {
    id: "pages/Sustainability";
    page: "/sustainability";
  };
  "pages/Node.tsx": {
    id: "pages/Node";
    page: "/node";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/home";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "Layout": typeof import("./src/Layout.tsx");
  "pages/Dashboard": typeof import("./src/pages/Dashboard.tsx");
  "pages/Blocks": typeof import("./src/pages/Blocks.tsx");
  "pages/BlockFeed": typeof import("./src/pages/BlockFeed.tsx");
  "pages/BlockDetail": typeof import("./src/pages/BlockDetail.tsx");
  "pages/Transaction": typeof import("./src/pages/Transaction.tsx");
  "pages/Address": typeof import("./src/pages/Address.tsx");
  "pages/Asset": typeof import("./src/pages/Asset.tsx");
  "pages/DexPairs": typeof import("./src/pages/DexPairs.tsx");
  "pages/UnconfirmedTransactions": typeof import("./src/pages/UnconfirmedTransactions.tsx");
  "pages/DistributionTool": typeof import("./src/pages/DistributionTool.tsx");
  "pages/TransactionMap": typeof import("./src/pages/TransactionMap.tsx");
  "pages/NetworkStatistics": typeof import("./src/pages/NetworkStatistics.tsx");
  "pages/NetworkMap": typeof import("./src/pages/NetworkMap.tsx");
  "pages/Peers": typeof import("./src/pages/Peers.tsx");
  "pages/Sustainability": typeof import("./src/pages/Sustainability.tsx");
  "pages/Node": typeof import("./src/pages/Node.tsx");
  "pages/Home": typeof import("./src/pages/Home.tsx");
};