name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        default: false
        description: Run without publishing
        type: boolean

concurrency:
  cancel-in-progress: false
  group: release

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: pnpm
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Biome format
        run: npx biome format .

      - name: Biome lint
        run: npx nx run-many -t biome-lint --projects='packages/*'

      - name: Typecheck
        run: npx nx run-many -t typecheck --projects='packages/*'

      - name: Build
        run: npx nx run-many -t build --projects='packages/*'

      - name: Test
        run: npx nx run-many -t test --projects='packages/*'

      - name: Verify package exports
        run: npx nx run-many -t check:exports --projects='packages/*'

      - name: Verify package publishing
        run: npx nx run-many -t check:publint --projects='packages/*' --exclude=ts-types

      - name: Verify bundle size
        run: npx nx run-many -t check:size --projects='packages/*'

      - name: Version
        run: npx nx release version --skip-publish ${{ inputs.dry-run && '--dry-run' || '' }}

      - name: Changelog
        run: npx nx release changelog --skip-publish ${{ inputs.dry-run && '--dry-run' || '' }}

      - name: Publish
        if: ${{ !inputs.dry-run }}
        run: npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
