name: Tests
on:
  push:
    branches-ignore:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run build
      - run: docker compose up --wait
      - run: npm test
      - if: ${{ always() }}
        run: docker compose down
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: test/videos
